<?php if(Mage::getStoreConfig('quickorder/settings/active')):?>
<?php $inputCount = Mage::getStoreConfig('quickorder/settings/default_count');
      $count = ($inputCount>0)?$inputCount:4;
	  $icon = Mage::getStoreConfig('quickorder/settings/default_icon');	
	  
	  $form_style = Mage::helper('quickorder/protected')->getConfig('form_style');
	  
	  $id = ($form_style=='lightbox')?'inline_lightbox':'quickorder_link';
	  $title = Mage::helper('quickorder/protected')->getConfig('form_title');
?>
<?php if($form_style=='lightbox' || $form_style=='collapse'):?>
<script type="text/javascript" src="<?php echo $this->getJsUrl('magecoders/configurable.js');?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('magecoders/autosuggest.js');?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('magecoders/quickorder.js');?>"></script>
<?php endif; ?>
<?php if($form_style=='lightbox'):?>
<script type="text/javascript" src="<?php echo $this->getJsUrl('magecoders/jquery.colorbox-min.js'); ?>"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/colorbox.css'); ?>" />
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery(".quickorder_box").colorbox({
			inline:true, html:true, width:"50%",
			onComplete:function(){
				var height = jQuery("#quickorder_box_lightbox").height() + 60;
				jQuery("#cboxContent").height(height);
				
				var top = parseInt(jQuery("#colorbox").css('top')) - 85;
				jQuery("#colorbox").css('top',top);
				
			},
			
			});
			
		jQuery('.sku').blur(function(){
			if(productLoaded){
			var nb = jQuery("#quickorder_box_lightbox").height() + 60;
			jQuery("#cboxContent").height(nb);
			}
		});
		jQuery("#add_item").click(function(){
			var height = jQuery("#quickorder_box_lightbox").height() + 60;
			jQuery("#cboxContent").height(height);
		});	
			
		
			
	});
</script>

<div class="quickorder_wrapper_lightbox">
	<a href="#quickorder_box_lightbox" class="quickorder_box">
	<?php if($icon!=''):?>
		<img src="<?php echo $this->getSkinUrl($icon); ?>" border="0" width="250" height="55" alt="Quick Order" />
	<?php else:?>
		<span>Quick Order</span>
	<?php endif; ?>
	</a>
	<div style="display:none;">
	
	<div id="quickorder_box_lightbox" style="background:#fff;"> 
	<?php if(!empty($title)):?>
		<h2><?php echo $title; ?></h2>
	<?php endif; ?>
	<form  id="quickorderFrm" name="quickorderFrm" onSubmit="return false;" method="post">
		<table width="100%" cellpadding="0" cellspacing="0" class="itemsBox">
			<tr>
				<td width="20%"><strong>Name / Sku #</strong></td>
				<td width="5%"><strong>Qty</strong></td>
				<td width="41%">&nbsp;</td>
				<td width="15%">&nbsp;</td>												
			</tr>
			<?php for($i=0; $i<$count; $i++):?>
				<tr id="row_<?php echo $i;?>">
					<td class="itemsku_<?php echo $i;?>"><input type="text" id="sku_<?php echo $i;?>" name="product[<?php echo $i;?>][sku]" title="sku_<?php echo $i; ?>" class="input-text sku"></td>
					<td class="itemqty_<?php echo $i;?>">
					<input type="text" id="qty_<?php echo $i; ?>" name="product[<?php echo $i;?>][qty]" class="input-text qty"></td>
					<td id="itemdata_<?php echo $i;?>">&nbsp;</td>
					<td class="a-right"><a href="javascript:;" class="remove" id="remove_<?php echo $i;?>"></a></td>															
				</tr>	
			<?php endfor; ?>
				<tr id="lastRow">
					<td></td>
				</tr>
			</table>
			<table width="100%">
				<tr>
					<td><a href="javascript:;" id="add_item">+ Add Item</a></td>
					<td></td>
				</tr>
			</table>
			<table width="100%" class="qck_bottom">
			<tr>
				<td colspan="2" class="f-left sc_msg"><span id="loader"></span></td>
				<td colspan="2" class="a-right">
				<button id="add_to_cart" onclick="submitQuickorderForm();" class="button btn-cart" title="Add to Cart" type="button"><span><span>ADD TO CART</span></span></button>
				</td>
			</tr>
			
		    </table>
	</div>
		<div class="Clear"></div>
<input type="hidden" name="quickorderAction" id="quickorderAction" value="<?php echo $this->getUrl('quickorder/index',array('_secure'=>true)); ?>"/>
	</form>
	</div>
	
	 
	
</div>

<?php elseif($form_style=='collapse'):?>

<div class="quickorder_wrapper">
	<a href="javascript:;" id="quickorder_link">
	<?php if($icon!=''):?>
		<img src="<?php echo $this->getSkinUrl($icon); ?>" border="0" width="250" height="55" />
	<?php else:?>
		<span>Quick Order</span>
	<?php endif; ?>
	</a>
	<div id="quickorder_box"  style="display:none;"> 
	<form  id="quickorderFrm" name="quickorderFrm" onSubmit="return false;" method="post">
		<table width="100%" cellpadding="0" cellspacing="0" class="itemsBox">
			<tr>
				<td width="20%"><strong>Name / Sku #</strong></td>
				<td width="5%"><strong>Qty</strong></td>
				<td width="41%">&nbsp;</td>
				<td width="15%">&nbsp;</td>												
			</tr>
			<?php for($i=0; $i<$count; $i++):?>
				<tr id="row_<?php echo $i;?>">
					<td class="itemsku_<?php echo $i;?>"><input type="text" id="sku_<?php echo $i;?>" name="product[<?php echo $i;?>][sku]" title="sku_<?php echo $i; ?>" class="input-text sku"></td>
					<td class="itemqty_<?php echo $i;?>">
					<input type="text" id="qty_<?php echo $i; ?>" name="product[<?php echo $i;?>][qty]" class="input-text qty"></td>
					<td id="itemdata_<?php echo $i;?>">&nbsp;</td>
					<td class="a-right"><a href="javascript:;" class="remove" id="remove_<?php echo $i;?>">x Remove</a></td>															
				</tr>	
			<?php endfor; ?>
				<tr id="lastRow">
					<td></td>
				</tr>
			</table>
			<table width="100%">
				<tr>
					<td><a href="javascript:;" id="add_item">+ Add Item</a></td>
					<td></td>
				</tr>
			</table>
			<table width="100%" class="qck_bottom">
			<tr>
				<td colspan="2" class="f-left sc_msg"><span id="loader"></span></td>
				<td colspan="2" class="a-right">
				<button id="add_to_cart" onclick="submitQuickorderForm();" class="button btn-cart" title="Add to Cart" type="button"><span><span>ADD TO CART</span></span></button>
				</td>
			</tr>
			<tr>
				<td><a href="javascript:;" id="quickorder_close">x Close</a></td>
				<td></td>				
			</tr>
		    </table>
	</div> 
	<div class="Clear"></div>
	<input type="hidden" name="quickorderAction" id="quickorderAction" value="<?php echo $this->getUrl('quickorder/index',array('_secure'=>true)); ?>"/>
	</form>
</div>

<?php endif; ?>

<?php endif; ?>