<?php echo '<h1>Categories</h1><pre>';
	echo $this->getRequest()->getParam('catid');
	$categoryHome = Mage::getModel('categoryhome/categoryhome');
	
	$categoryObj = Mage::getModel('catalog/category');
	$categories = $categoryObj->getCollection()
													->addAttributeToFilter('level', 2)//2 is actually the first level
													->addAttributeToFilter('is_active', 1);
	
	 
	?> 
	<div class="cat_container">
	<?php
	foreach ($categories->getData() as $_category) { 
		$parCat = $categoryObj->load($_category['entity_id']);
		echo '<div class="cat_name">'.$parCat->getName().'</div>';
		echo '<div class="cat_name">'.$parCat->getChildren().'</div>';
		
		echo '<div class="cat_image">'.$parCat->getImage().'</div>';
		
		
		/* $productCollection = Mage::getModel('catalog/product')
                            ->getCollection()
                             ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left') 
                            ->addAttributeToSelect('*')
							->addAttributeToFilter('category_id', $_category['entity_id'])
							//->getSelect()->limit(4)
							;
							 */
					
	

// print_r($productslist)
 /* $category_id = $_category['entity_id']; // if you know static category then enter number

$catagory_model = Mage::getModel('catalog/category')->load($category_id); 

$collection = Mage::getResourceModel('catalog/product_collection');

$collection->addCategoryFilter($catagory_model); //category filter

$collection->addAttributeToFilter('status',1); //only enabled product

$collection->addAttributeToSelect(array('name','url','small_image')); //add product attribute to be fetched

$collection->getSelect()->order('rand()')->limit(10); //uncomment to get products in random order     

$collection->addStoreFilter();  */
	$collection = $categoryHome->getCategoryProducts($category_id);
	
	print_r($collection->getData()); 
		if(!empty($collection))
		{
			foreach ($collection as $_product):?>
				<a href="<?php echo $_product->getProductUrl();?>"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'small_image')->resize(197, 167); ?>" />   </a>
				<div><?php echo $_product->getName();?></div>
			 <?php   endforeach;
			}else
				{
					echo 'No products exists';
			} 

		//print_r($parCat->getData());
		
		
	}
	
?> 
</div>
